const keyData = {
  en: [
    {
      code: 'Backquote',
      value: '`',
      shift: '~',
      row: 0,
    },
    {
      code: 'Digit1',
      value: '1',
      shift: '!',
      row: 0,
    },
    {
      code: 'Digit2',
      value: '2',
      shift: '@',
      row: 0,
    },
    {
      code: 'Digit3',
      value: '3',
      shift: '#',
      row: 0,
    },
    {
      code: 'Digit4',
      value: '4',
      shift: '$',
      row: 0,
    },
    {
      code: 'Digit5',
      value: '5',
      shift: '%',
      row: 0,
    },
    {
      code: 'Digit6',
      value: '6',
      shift: '^',
      row: 0,
    },
    {
      code: 'Digit7',
      value: '7',
      shift: '&',
      row: 0,
    },
    {
      code: 'Digit8',
      value: '8',
      shift: '*',
      row: 0,
    },
    {
      code: 'Digit9',
      value: '9',
      shift: '(',
      row: 0,
    },
    {
      code: 'Digit0',
      value: '0',
      shift: ')',
      row: 0,
    },
    {
      code: 'Minus',
      value: '-',
      shift: '_',
      row: 0,
    },
    {
      code: 'Equal',
      value: '=',
      shift: '+',
      row: 0,
    },
    {
      code: 'Backspace',
      value: 'Backspace',
      shift: null,
      row: 0,
    },
    {
      code: 'Tab',
      value: 'Tab',
      shift: null,
      row: 1,
    },
    {
      code: 'KeyQ',
      value: 'q',
      shift: 'Q',
      row: 1,
    },
    {
      code: 'KeyW',
      value: 'w',
      shift: 'W',
      row: 1,
    },
    {
      code: 'KeyE',
      value: 'e',
      shift: 'E',
      row: 1,
    },
    {
      code: 'KeyR',
      value: 'r',
      shift: 'R',
      row: 1,
    },
    {
      code: 'KeyT',
      value: 't',
      shift: 'T',
      row: 1,
    },
    {
      code: 'KeyY',
      value: 'y',
      shift: 'Y',
      row: 1,
    },
    {
      code: 'KeyU',
      value: 'u',
      shift: 'U',
      row: 1,
    },
    {
      code: 'KeyI',
      value: 'i',
      shift: 'I',
      row: 1,
    },
    {
      code: 'KeyO',
      value: 'o',
      shift: 'O',
      row: 1,
    },
    {
      code: 'KeyP',
      value: 'p',
      shift: 'P',
      row: 1,
    },
    {
      code: 'BracketLeft',
      value: '[',
      shift: '{',
      row: 1,
    },
    {
      code: 'BracketRight',
      value: ']',
      shift: '}',
      row: 1,
    },
    {
      code: 'Backslash',
      value: '\\',
      shift: '|',
      row: 1,
    },
    {
      code: 'Delete',
      value: 'Del',
      shift: null,
      row: 1,
    },
    {
      code: 'CapsLock',
      value: 'CapsLock',
      shift: null,
      row: 2,
    },
    {
      code: 'KeyA',
      value: 'a',
      shift: 'A',
      row: 2,
    },
    {
      code: 'KeyS',
      value: 's',
      shift: 'S',
      row: 2,
    },
    {
      code: 'KeyD',
      value: 'd',
      shift: 'D',
      row: 2,
    },
    {
      code: 'KeyF',
      value: 'f',
      shift: 'F',
      row: 2,
    },
    {
      code: 'KeyG',
      value: 'g',
      shift: 'G',
      row: 2,
    },
    {
      code: 'KeyH',
      value: 'h',
      shift: 'H',
      row: 2,
    },
    {
      code: 'KeyJ',
      value: 'j',
      shift: 'J',
      row: 2,
    },
    {
      code: 'KeyK',
      value: 'k',
      shift: 'K',
      row: 2,
    },
    {
      code: 'KeyL',
      value: 'l',
      shift: 'L',
      row: 2,
    },
    {
      code: 'Semicolon',
      value: ';',
      shift: ':',
      row: 2,
    },
    {
      code: 'Quote',
      value: "'",
      shift: '"',
      row: 2,
    },
    {
      code: 'Enter',
      value: 'Enter',
      shift: null,
      row: 2,
    },
    {
      code: 'ShiftLeft',
      value: 'Shift',
      shift: null,
      row: 3,
    },
    {
      code: 'KeyZ',
      value: 'z',
      shift: 'Z',
      row: 3,
    },
    {
      code: 'KeyX',
      value: 'x',
      shift: 'X',
      row: 3,
    },
    {
      code: 'KeyC',
      value: 'c',
      shift: 'C',
      row: 3,
    },
    {
      code: 'KeyV',
      value: 'v',
      shift: 'V',
      row: 3,
    },
    {
      code: 'KeyB',
      value: 'b',
      shift: 'B',
      row: 3,
    },
    {
      code: 'KeyN',
      value: 'n',
      shift: 'N',
      row: 3,
    },
    {
      code: 'KeyM',
      value: 'm',
      shift: 'M',
      row: 3,
    },
    {
      code: 'Comma',
      value: ',',
      shift: '<',
      row: 3,
    },
    {
      code: 'Period',
      value: '.',
      shift: '>',
      row: 3,
    },
    {
      code: 'Slash',
      value: '/',
      shift: '?',
      row: 3,
    },
    {
      code: 'ArrowUp',
      value: '⇧',
      shift: null,
      row: 3,
    },
    {
      code: 'ShiftRight',
      value: 'Shift',
      shift: null,
      row: 3,
    },
    {
      code: 'ControlLeft',
      value: 'Ctrl',
      shift: null,
      row: 4,
    },
    {
      code: 'MetaLeft',
      value: 'Win',
      shift: null,
      row: 4,
    },
    {
      code: 'AltLeft',
      value: 'Alt',
      shift: null,
      row: 4,
    },
    {
      code: 'Space',
      value: ' ',
      shift: null,
      row: 4,
    },
    {
      code: 'AltRight',
      value: 'Alt',
      shift: null,
      row: 4,
    },
    {
      code: 'ArrowLeft',
      value: '⇦',
      shift: null,
      row: 4,
    },
    {
      code: 'ArrowDown',
      value: '⇩',
      shift: null,
      row: 4,
    },
    {
      code: 'ArrowRight',
      value: '⇨',
      shift: null,
      row: 4,
    },
    {
      code: 'ControlRight',
      value: 'Ctrl',
      shift: null,
      row: 4,
    },
  ],
  ru: [
    {
      code: 'Backquote',
      value: 'ё',
      shift: 'Ё',
      row: 0,
    },
    {
      code: 'Digit1',
      value: '1',
      shift: '!',
      row: 0,
    },
    {
      code: 'Digit2',
      value: '2',
      shift: '"',
      row: 0,
    },
    {
      code: 'Digit3',
      value: '3',
      shift: '№',
      row: 0,
    },
    {
      code: 'Digit4',
      value: '4',
      shift: ';',
      row: 0,
    },
    {
      code: 'Digit5',
      value: '5',
      shift: '%',
      row: 0,
    },
    {
      code: 'Digit6',
      value: '6',
      shift: ':',
      row: 0,
    },
    {
      code: 'Digit7',
      value: '7',
      shift: '?',
      row: 0,
    },
    {
      code: 'Digit8',
      value: '8',
      shift: '*',
      row: 0,
    },
    {
      code: 'Digit9',
      value: '9',
      shift: '(',
      row: 0,
    },
    {
      code: 'Digit0',
      value: '0',
      shift: ')',
      row: 0,
    },
    {
      code: 'Minus',
      value: '-',
      shift: '_',
      row: 0,
    },
    {
      code: 'Equal',
      value: '=',
      shift: '+',
      row: 0,
    },
    {
      code: 'Backspace',
      value: 'Backspace',
      shift: null,
      row: 0,
    },
    {
      code: 'Tab',
      value: 'Tab',
      shift: null,
      row: 1,
    },
    {
      code: 'KeyQ',
      value: 'й',
      shift: 'Й',
      row: 1,
    },
    {
      code: 'KeyW',
      value: 'ц',
      shift: 'Ц',
      row: 1,
    },
    {
      code: 'KeyE',
      value: 'у',
      shift: 'У',
      row: 1,
    },
    {
      code: 'KeyR',
      value: 'к',
      shift: 'К',
      row: 1,
    },
    {
      code: 'KeyT',
      value: 'е',
      shift: 'Е',
      row: 1,
    },
    {
      code: 'KeyY',
      value: 'н',
      shift: 'Н',
      row: 1,
    },
    {
      code: 'KeyU',
      value: 'г',
      shift: 'Г',
      row: 1,
    },
    {
      code: 'KeyI',
      value: 'ш',
      shift: 'Ш',
      row: 1,
    },
    {
      code: 'KeyO',
      value: 'щ',
      shift: 'Щ',
      row: 1,
    },
    {
      code: 'KeyP',
      value: 'з',
      shift: 'З',
      row: 1,
    },
    {
      code: 'BracketLeft',
      value: 'х',
      shift: 'Х',
      row: 1,
    },
    {
      code: 'BracketRight',
      value: 'ъ',
      shift: 'Ъ',
      row: 1,
    },
    {
      code: 'Backslash',
      value: '\\',
      shift: '/',
      row: 1,
    },
    {
      code: 'Delete',
      value: 'Del',
      shift: null,
      row: 1,
    },
    {
      code: 'CapsLock',
      value: 'CapsLock',
      shift: null,
      row: 2,
    },
    {
      code: 'KeyA',
      value: 'ф',
      shift: 'Ф',
      row: 2,
    },
    {
      code: 'KeyS',
      value: 'ы',
      shift: 'Ы',
      row: 2,
    },
    {
      code: 'KeyD',
      value: 'в',
      shift: 'В',
      row: 2,
    },
    {
      code: 'KeyF',
      value: 'а',
      shift: 'А',
      row: 2,
    },
    {
      code: 'KeyG',
      value: 'п',
      shift: 'П',
      row: 2,
    },
    {
      code: 'KeyH',
      value: 'р',
      shift: 'Р',
      row: 2,
    },
    {
      code: 'KeyJ',
      value: 'о',
      shift: 'О',
      row: 2,
    },
    {
      code: 'KeyK',
      value: 'л',
      shift: 'Л',
      row: 2,
    },
    {
      code: 'KeyL',
      value: 'д',
      shift: 'Д',
      row: 2,
    },
    {
      code: 'Semicolon',
      value: 'ж',
      shift: 'Ж',
      row: 2,
    },
    {
      code: 'Quote',
      value: 'э',
      shift: 'Э',
      row: 2,
    },
    {
      code: 'Enter',
      value: 'Enter',
      shift: null,
      row: 2,
    },
    {
      code: 'ShiftLeft',
      value: 'Shift',
      shift: null,
      row: 3,
    },
    {
      code: 'KeyZ',
      value: 'я',
      shift: 'Я',
      row: 3,
    },
    {
      code: 'KeyX',
      value: 'ч',
      shift: 'Ч',
      row: 3,
    },
    {
      code: 'KeyC',
      value: 'с',
      shift: 'С',
      row: 3,
    },
    {
      code: 'KeyV',
      value: 'м',
      shift: 'М',
      row: 3,
    },
    {
      code: 'KeyB',
      value: 'и',
      shift: 'И',
      row: 3,
    },
    {
      code: 'KeyN',
      value: 'т',
      shift: 'Т',
      row: 3,
    },
    {
      code: 'KeyM',
      value: 'ь',
      shift: 'Ь',
      row: 3,
    },
    {
      code: 'Comma',
      value: 'б',
      shift: 'Б',
      row: 3,
    },
    {
      code: 'Period',
      value: 'ю',
      shift: 'Ю',
      row: 3,
    },
    {
      code: 'Slash',
      value: '.',
      shift: ',',
      row: 3,
    },
    {
      code: 'ArrowUp',
      value: '⇧',
      shift: null,
      row: 3,
    },
    {
      code: 'ShiftRight',
      value: 'Shift',
      shift: null,
      row: 3,
    },
    {
      code: 'ControlLeft',
      value: 'Ctrl',
      shift: null,
      row: 4,
    },
    {
      code: 'MetaLeft',
      value: 'Win',
      shift: null,
      row: 4,
    },
    {
      code: 'AltLeft',
      value: 'Alt',
      shift: null,
      row: 4,
    },
    {
      code: 'Space',
      value: ' ',
      shift: null,
      row: 4,
    },
    {
      code: 'AltRight',
      value: 'Alt',
      shift: null,
      row: 4,
    },
    {
      code: 'ArrowLeft',
      value: '⇦',
      shift: null,
      row: 4,
    },
    {
      code: 'ArrowDown',
      value: '⇩',
      shift: null,
      row: 4,
    },
    {
      code: 'ArrowRight',
      value: '⇨',
      shift: null,
      row: 4,
    },
    {
      code: 'ControlRight',
      value: 'Ctrl',
      shift: null,
      row: 4,
    },
  ],
};
export default keyData